### ISSUE TITLE
"Приклеенные" свойства устройства - постоянно опрашивать значения некоторых свойств

### ISSUE THREAD

**Issue by sadr0b0t** [1i7/babbler-js#18]
"Приклеенные" свойства устройства - постоянно опрашивать значения некоторых свойств у робота. Достаточно частый сценарий, когда нужно постноянно иметь актуальное значение некоторого свойства (статус задания, координаты рабочего блока станка и т.п.). 

Отдавать опрос на откуп клиентам можно, но не очень удобно, т.к. для при реализации постоянного опроса могуть вылезти некоторые нюансы при работе с очередью, добавлять один и тот же код для каждого свойства, тем более вносить аналогичные исправления во все места довольно утомительно. При этом задача вполне типовая, по факту реализация любого устройства всегда будет начинаться с определения свойств, для которых нам нужен постоянно актуальный статус, а уже потом будут управляющие команды пользователя.

Плюс, выделив для статусных команд отдельный АПИ, их будет проще отделять от пользовательских (см https://github.com/1i7/babbler-js/issues/17).

Пример - опрос статуса станка (работает/ожидает) и текущей позиции рабочего инструмента в babbler-cnc
https://github.com/1i7/babbler-robots/blob/519cd6b73258926980f25e160cfb2bf1de5d3c68/babbler-cnc/babbler-cnc-js/src/babbler-cnc.js#L94

~~~js
 // опрашивать текущий статус рабочего инструмента
    var _getStatus = function() {
        // отправлять новый запрос только в том случае,
        // если получили ответ на предыдущий
        if(!_statusWaitReply) {
            _statusWaitReply = true;
            _babbler.sendCmd("status", [],
                // onResult
                function(err, reply, cmd, params) {
                    _statusWaitReply = false;
                    if(err) {
                        _cncStatusErr = err;
                    } else {
                        _cncStatus = reply;
                    }
                    this.emit(BabblerCncEvent.STATUS, _cncStatus, err);
                }.bind(this)
            );
        }
    }.bind(this);
    
    // опрашивать текущее положение рабочего инструмента
    var _getPos = function() {
        // отправлять новый запрос только в том случае,
        // если получили ответ на предыдущий
        if(!_posWaitReply) {
            _posWaitReply = true;
            _babbler.sendCmd("pos", [],
                // onResult
                function(err, reply, cmd, params) {
                    _posWaitReply = false;
                    if(err) {
                        _posErr = err;
                        this.emit(BabblerCncEvent.POSITION, undefined, err);
                    } else if(_rawPos !== reply) {
                        _rawPos = reply;
                        
                        var posArr = _rawPos.split(" ");
                        _pos.x = parseInt(posArr[0], 10);
                        _pos.y = parseInt(posArr[1], 10);
                        _pos.z = parseInt(posArr[2], 10);
                        
                        this.emit(BabblerCncEvent.POSITION, _pos, undefined);
                    }
                }.bind(this)
            );
        }
}.bind(this);
~~~

**Нужно добавить** 
- вызов "stickProp" ("приклеить" свойство), параметры cmd, params (+может быть, имя свойства)
- период опроса: один раз (при подключении) или регулярно с заданным таймаутом
- событие property_change (cmd, params, err, reply)
- getProp - получить значение свойства, параметры (cmd, params) или по имени (тогда регистрировать нужно тоже по имени).

**Comment by 1i7** [comment]
Есть.

https://github.com/1i7/babbler-js/commit/03145247b4d7ea7767fa2288724ce67ba94e0168

Приклеить свойства:

будет запрошено один раз при подключении
~~~js
    babbler.stickProp("name", "name", []);
    babbler.stickProp("manufacturer", "manufacturer", []);
~~~

будут постоянно опрашиваться 2 раза в секунду (каждые 500 миллисекунд)
~~~js
    babbler.stickProp("name", "name", [], 500);
    babbler.stickProp("manufacturer", "manufacturer", [], 500);
~~~

Здесь первый параметр - имя свойства, второй - команда для устройства, 3й - параметры команды, 4й - период опроса (0 - запрашивать один раз при подключении).

Получить значение свойства:

~~~js
babbler.getStickedProp("name").val
~~~

Если при отправке команды произошла ошибка
~~~js
babbler.getStickedProp("name").err
~~~

Глобальное событие при изменении значения свойства:
~~~js
babbler.on('prop', function(name, err, val) {
    //...
}
~~~

Пожалуй, нужно что-то еще придумать с ситуацией, когда свойства с period=0 (запрашивать только один раз при подключении) не смогли получить значение с первой попытки после подключения (например, переполнилась очередь команд или сработал таймаут или типа того), при этом связь не разорвалась. Для регулярно обновляемых свойств это не проблема, т.к. запрос все равно будет отправлен еще раз автоматом. Для неизменяемых свойств, пожалуй, будет достаточно добавить возможность запросить значения свойств вручную (в интерфейс пользователя вынести специальную кнопку на этот случай). Ну и желательно минимизировать возможность такой ситуации (те же приоритеты для команд - например, не выкидывать их из очереди).

**Comment by 1i7** [comment]
добавил requestStickedProps - отправить внеочередные запросы для получения значений всех "приклеенных" свойств:
https://github.com/1i7/babbler-js/commit/6d53a79ef28d03ee572f860a62af5c56ec7654f6

и здесь достаточно. Приоритеты тоже желательно реализовать (если будет много свойств, они при достаточно высокой частоте опроса будут гарантированно забивать всю очередь), но в своем тикете.
